trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

# Define multi-stage pipeline
stages:
  - stage: InitialSetup
    jobs:
      - job: HelloWorld
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'

  - stage: Build_Account_Service
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'account-service/pom.xml'
              goals: 'clean test'
