spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
axon:
  eventhandling:
    processors:
      transactionProcessor:
        mode: tracking
        source: kafka
server:
  port: 8081
