server:
  port: 8085
spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      database: mydatabase
      uri: mongodb://localhost:27017
      authentication-database: admin
      username: myuser
      password: ${mypassword}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

#axon:
#  eventhandling:
#    processors:
#      transactionProcessor:
#        mode: tracking
#        source: kafka

