name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_REPO: your-dockerhub-repo
      SONARQUBE_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
      SONARQUBE_LOGIN: ${{ secrets.SONARQUBE_LOGIN }}

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >
          --health-cmd="curl -f http://localhost:9000/api/system/health"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Code Analysis with SonarQube
        run: mvn sonar:sonar
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
          SONAR_LOGIN: ${{ secrets.SONARQUBE_LOGIN }}

      - name: Build Docker Image for User Service
        run: docker build -t $DOCKER_HUB_REPO/user-service ./user-service

      - name: Build Docker Image for Account Service
        run: docker build -t $DOCKER_HUB_REPO/account-service ./account-service

      - name: Build Docker Image for Transaction Service
        run: docker build -t $DOCKER_HUB_REPO/transaction-service ./transaction-service

      - name: Push Docker Images to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $DOCKER_HUB_REPO/user-service
          docker push $DOCKER_HUB_REPO/account-service
          docker push $DOCKER_HUB_REPO/transaction-service
