server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, trace
  health:
    mail:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

