spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://your-production-db-url:5432/userdb_prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
management:
  endpoints:
    web:
      exposure:
        include: health, info