
# Production Profile
---
spring:
  profiles:
    active: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5444/account_db}
    username: ${DATABASE_USERNAME:your_name}
    password: ${DATABASE_PASSWORD:your_password}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
        hostname: localhost
