version: "3.9"
services:
  user_service:
    container_name: user_service
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
      - DB_PORT=6543
    depends_on:
      - user_service_db

  user_service_db:
    image: postgres:latest
    ports:
      - "5432:5422"

volumes:
  user_db:

