version: "3.9"
services:
  account-service:
    container_name: account-service
    build:
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_BOOT_PROFILE=prod
      - DATABASE_URL=jdbc:postgresql://postgres_account:5432/account_db
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres_account

  postgres_account:
    image: postgres:latest
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: your_name
      POSTGRES_PASSWORD: your_password
    volumes:
      - account_db:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - bank-network

volumes:
  account_db:
networks:
  bank-network:

