server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stainley/bank-showcase.git
          clone-on-start: true
          default-label: main
          search-paths: config
      discovery:
        enabled: true
  application:
    name: config-server
  security:
    user:
      name: config-user
      password: config-password
